# Generated by Django 4.0.4 on 2022-05-16 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timmi_app', '0002_alter_products_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('description', models.CharField(max_length=255)),
                ('discount', models.FloatField()),
            ],
        ),
    ]
